import type { Entry } from "./types";

/**
 * Every post on the site.
 * Add a new object to this list. See content/README.md for which section does what.
 * Order inside a section is the order on the page.
 */

function placeholder(
  id: string,
  section: Entry["section"],
  index: string,
  date: string,
): Entry {
  return {
    id,
    section,
    index,
    date,
    title: `Untitled — Entry ${index}`,
    spine: "Untitled",
    dek: "Awaiting dispatch.",
    body: "[ Entry forthcoming. ]",
    tags: [],
    draft: true,
  };
}

export const ENTRIES: Entry[] = [
  {
    id: "mendocino",
    section: "destinations",
    index: "01.04",
    date: "09.2026",
    place: "Mendocino",
    title: "Mendocino",
    dek: "Oddly felt like home.",
    body: "Waking up without an agenda. Staying at a vegan eco-friendly inn. Getting to know the locals at both Fort Bragg and Mendocino Village. Solo hikes (when Truffles was too tired) in the redwood forest. Secluded beaches for sunset. Oh and hanging out with horses, donkeys, llamas... I mean I never wanted to come back. Oddly felt like home",
    pin: [39.3077, -123.7995],
    arrive: "paddle",
    images: [
      "/destinations/mendocino/mendocino-01.jpg",
      "/destinations/mendocino/mendocino-02.jpg",
      "/destinations/mendocino/mendocino-03.jpg",
      "/destinations/mendocino/mendocino-04.jpg",
      "/destinations/mendocino/mendocino-05.jpg",
      "/destinations/mendocino/mendocino-06.jpg",
      "/destinations/mendocino/mendocino-07.jpg",
      "/destinations/mendocino/mendocino-08.jpg",
      "/destinations/mendocino/mendocino-09.jpg",
    ],
    imageAlts: [
      "Truffles resting in the shade of a pine on a bluff above a sandy cove and blue ocean",
      "Watercolors and brushes on a deck table, a flower painting in progress, Truffles wandering past purple blooms",
      "Driftwood glowing in late sun on a sandy riverbank across from a dark forest",
      "Rocks and a curling tide where the river meets the beach, hills lit orange at sunset",
      "Sunset over a beach and river mouth, driftwood at the water's edge",
      "Selfie on the rocky coast with Truffles, sea spray behind",
      "A river winding between forested hills and marsh under a soft cloudy sky",
      "Truffles eyeing a plate of dog treats on a patio table overlooking the hills",
      "Selfie on a wooden deck by a still lagoon, Truffles lying on the boards",
    ],
    imageAspects: [
      "landscape",
      "portrait",
      "landscape",
      "landscape",
      "landscape",
      "portrait",
      "landscape",
      "landscape",
      "landscape",
    ],
    tags: [],
  },
  {
    id: "hawaii",
    section: "destinations",
    index: "01.03",
    date: "07-08.2026",
    place: "Hawaii",
    title: "Hawaii",
    dek: "Outdoor showers only.",
    pin: [22.2, -159.5],
    arrive: "fly",
    body: "I basically moved my body all day and it felt great. But, my favorite part of the trip was taking outdoor showers while feeling the sun beating down, listening to the ocean + birds, and smelling a combination of lavender + nature ..... I can't tell you how much that regulated my nervous system. I don't think I took a shower indoors once that trip",
    images: [
      "/hawaii/hawaii-01.jpg",
      "/hawaii/hawaii-02.jpg",
      "/hawaii/hawaii-03.jpg",
      "/hawaii/hawaii-04.jpg",
      "/hawaii/hawaii-05.jpg",
      "/hawaii/hawaii-06.jpg",
    ],
    imageAlts: [
      "Paddleboarding off a green headland",
      "Standing in shallow water beside an outrigger canoe",
      "Rooftop garden facing a sunset coast",
      "Night beach with a palm and kayaks",
      "On a catamaran under a yellow sail",
      "Feet toward a beach tree and the horizon",
    ],
    imageAspects: [
      "portrait",
      "landscape",
      "landscape",
      "portrait",
      "portrait",
      "portrait",
    ],
    tags: [],
  },

  {
    id: "colombia",
    section: "destinations",
    index: "01.02",
    date: "06.2026",
    place: "Colombia",
    title: "Colombia",
    dek: "Where I learned to salsa.",
    body: "[ Entry forthcoming. ]",
    pin: [6.2442, -75.5812],
    arrive: "fly",
    images: [
      "/destinations/colombia/colombia-01.jpg",
      "/destinations/colombia/colombia-02.jpg",
      "/destinations/colombia/colombia-03.jpg",
      "/destinations/colombia/colombia-04.jpg",
      "/destinations/colombia/colombia-05.jpg",
      "/destinations/colombia/colombia-06.jpg",
      "/destinations/colombia/colombia-07.jpg",
      "/destinations/colombia/colombia-08.jpg",
    ],
    imageAlts: [
      "A café with a live-edge wood bar and walls of bookshelves",
      "Two friends smiling and raising cocktails, one pale green, one berry red",
      "A hillside city of red-brick high-rises and green trees, seen from a treadmill",
      "Two friends at a dinner table holding up hands covered in chocolate",
      "Petit fours on charred wooden stands beside a glass of champagne",
      "A slice of chocolate cake with cream and two cortados on a concrete table",
      "Dancing salsa with a partner in a studio",
      "A black-and-white photo of a new floral tattoo on a shoulder blade",
    ],
    imageAspects: [
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
    ],
    // Where each photo was taken. Leave "" for no caption.
    imageCaptions: ["", "", "", "", "", "", "", ""],
    featured: [{ src: "/destinations/colombia/colombia-08.jpg" }],
    tags: [],
  },
  {
    id: "mexico-city",
    section: "destinations",
    index: "01.01",
    date: "06.2026",
    place: "Mexico City",
    title: "Mexico City",
    dek: "Mostly for food.",
    body: [
      "Mexico City holds a special place in my heart. This was my 4th trip there but I found so many new aspects of myself. Three highlights:",
      "* Experiencing the omakase tasting at Pujol where I serendipitously met Javi - an incredible human and winemaker at Peter Michael (Californians are everywhere). I was inspired by how much he loved what he did, the art and science being his craft, and that twinkle in his eye when he spoke about building his own thing. Something shifted inside of me and I sent my resignation letter right then and there. He said, “Well, I'll always remember this - meeting a stranger and being part of her quitting her job”. We ended up checking out the cocktail scene that night and I made a new friend that I can't wait to create more memories with\n* Discovered Xinu - obsessed with the intentionality and local ingredients that go into their perfumes. I tried verti-verde and left thinking this smells exactly how I feel. Needless to say I found my signature scent\n* Catching world cup games - the pure joy of connecting with others while rooting for Mexico. Everyone seemed to forget all of the divisions and turmoil in the world, and honestly it was SO NICE being away from the AI dystopia that is San Francisco. I had started to feel that I was the odd one out when I didn't want to talk about valuations, what AI tool you're building, and how we're all heading straight towards AGI -- rendering humans useless.",
    ].join("\n\n"),
    pin: [19.4326, -99.1332],
    arrive: "fly",
    images: [
      "/destinations/mexico-city/mexico-city-01.jpg",
      "/destinations/mexico-city/mexico-city-02.jpg",
      "/destinations/mexico-city/mexico-city-03.jpg",
      "/destinations/mexico-city/mexico-city-04.jpg",
      "/destinations/mexico-city/mexico-city-05.jpg",
      "/destinations/mexico-city/mexico-city-06.jpg",
      "/destinations/mexico-city/mexico-city-07.jpg",
      "/destinations/mexico-city/mexico-city-08.jpg",
      "/destinations/mexico-city/mexico-city-09.jpg",
      "/destinations/mexico-city/mexico-city-10.jpg",
    ],
    imageAlts: [
      "Three tacos on pink tortillas with a pink smoothie on a marble table",
      "A cup of gelato held up in front of the lit-up Don Nino gelateria at night",
      "Biting into a pastry from a paper bag in a leafy park",
      "A mirror selfie framed by smooth concrete walls",
      "A plated dessert beside a copy of Violeta by Isabel Allende, parrot wallpaper behind",
      "A tree-lined street corner with an old building, a red car and a crosswalk",
      "A Tout Chocolat takeaway cup on a wooden tray",
      "A chalkboard sign on the sidewalk: a soccer ball melting into chocolate",
      "A place setting with a pink Masala & Maíz menu and a denim napkin",
      "Mole sprinkled with sesame on a spotted ceramic plate at Pujol",
    ],
    imageAspects: [
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "landscape",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
    ],
    // Where each photo was taken. Leave "" for no caption.
    imageCaptions: [
      "La Pitahaya Vegana",
      "Don Nino gelateria",
      "Café Rosetta",
      "",
      "Panadería Rosetta",
      "",
      "Tout Chocolat",
      "",
      "Masala & Maíz",
      "Pujol",
    ],
    tags: [],
  },

  {
    id: "salsa-week-one",
    section: "play",
    hobby: "dance",
    index: "02.01",
    date: "06.2026",
    title: "Huh, salsa. Who knew?",
    dek: "",
    body: "My first week learning salsa, actually me in brown might even be my second day... and it taught me a lot. It allowed me to stop thinking so much and just be in my body. It was a flow state very different from what I've experienced when working (that cerebral locked-in flow vs being sensual and free). This was back in June and I've grown so much as a salsera since then ..... but one thing I'm still trying to overcome, the need for perfection before dancing with someone new. Come dance with me at Cigar bar in SF? We can make mistakes together :)",
    videos: [
      {
        src: "/play/salsa-01.mp4",
        poster: "/play/salsa-01.jpg",
        aspect: "portrait",
      },
      {
        src: "/play/salsa-02.mp4",
        poster: "/play/salsa-02.jpg",
        aspect: "portrait",
      },
    ],
    tags: [],
  },
  {
    // Opens the studio wall. Add paintings and notes in content/studio.ts.
    id: "studio",
    section: "play",
    hobby: "painting",
    index: "02.02",
    date: "",
    title: "The studio wall",
    dek: "More to come!",
    body: "",
    tags: [],
  },

  { ...placeholder("farmers-market", "play", "02.03", "09.14.2026"), hobby: "market" },
  {
    // The typed page on the Play table: opens the list of ponderings (section "mood" below).
    id: "ponderings",
    section: "play",
    hobby: "writing",
    index: "02.04",
    date: "",
    title: "Ponderings",
    dek: "",
    body: "",
    tags: [],
  },

  placeholder("shelf-book-01", "bookshelf", "03.01", "09.05.2026"),
  placeholder("shelf-book-02", "bookshelf", "03.02", "09.10.2026"),
  placeholder("shelf-book-03", "bookshelf", "03.03", "09.15.2026"),
  placeholder("shelf-book-04", "bookshelf", "03.04", "09.19.2026"),
  placeholder("shelf-book-05", "bookshelf", "03.05", "09.20.2026"),
  placeholder("shelf-book-06", "bookshelf", "03.06", "09.20.2026"),
  { ...placeholder("shelf-podcast-01", "bookshelf", "03.07", "09.21.2026"), format: "podcast" },
  { ...placeholder("shelf-podcast-02", "bookshelf", "03.08", "09.21.2026"), format: "podcast" },
  { ...placeholder("shelf-podcast-03", "bookshelf", "03.09", "09.22.2026"), format: "podcast" },

  placeholder("mood-log-01", "mood", "04.01", "09.07.2026"),
  placeholder("mood-log-02", "mood", "04.02", "09.13.2026"),
  placeholder("mood-log-03", "mood", "04.03", "09.18.2026"),
  {
    id: "think-and-we-are",
    section: "mood",
    index: "04.04",
    date: "",
    title: "Can you hold both at once?",
    dek: "Work in progress.",
    body: "How to hold both of these at once, “I think, therefore I am” and “I am because we are”, and what they mean to me.",
    tags: [],
  },
  {
    id: "ritual-of-coffee",
    section: "mood",
    index: "04.05",
    date: "08.28.2026",
    title: "The Ritual of Coffee",
    dek: "",
    body: [
      "That first sip feels like relief. The warming layers, the smoothness, such a delicate balance of flavors, and the immediate signal to my brain that it's go time.",
      "That's the power of a ritual. It's different from a habit or doing something for the sake of the function. It's a bit more sacred, and always intentional. It becomes so essential and ingrained in your life, at the chosen intervals, that any removal feels deeply unsettling.",
      "The question is: is it the ritual itself, or the object? Is it the impact of the stimulant on the nervous system, or, if you believe in this stuff, the soul? If I had to wager, it's the deeper meaning, often related to pleasure, even in a quiet, subtle way. Rather than a brain dopamine hit, it's the gentle steadiness of my morning walk with Truffles, or a slow skincare routine. This is the magic of coffee for me.",
      "From the second I wake up, it doesn't matter where in the world I am, what yesterday looked like, or what today holds. I know this is my me time. What I find once I'm out the door may be a delightful surprise, whether it's the location, the café, or an interaction. When I walk into a café, it feels like a common thread that connects people across cultures. I could be in India, in Paris, in Colombia, and immediately feel like I belong, like I have a space to settle if I so desire, free to dive into conversation or stay a wallflower sipping my cup.",
      "And it doesn't have to be somewhere far away. The cafés I cycle between, Saint Frank, Spro, and Blue Bottle, are all within a five-minute walk, and they feel just as sacred. My order is an oat latte or an oat cappuccino, depending on the day. Close to home, it's a mix of flavor, pleasure, familiarity, and groundedness, and these days very little about utility. I feel like I'm part of a community.",
      "Here's the contradiction: I call it the magic of coffee, yet it's not really about the coffee at all. It has to be palatable, sure. I know good beans, enough to be competent without being a snob, but it doesn't even matter how good the drink is. And still, nothing else will do. I'm not as satisfied or grounded when I have chai. I have a relationship with coffee that can't be replaced, at least if we're staying in the realm of ritual and keeping utility at arm's length.",
      "So now I'm curious about yours. What's the small thing you do that feels sacred instead of routine? A crossword, the way you make your tea? When did it become a ritual, and what happens when you skip it? Tell me. I'd love to understand what ritual means to you.",
    ].join("\n\n"),
    tags: [],
  },

  {
    id: "spanish-lessons",
    section: "next",
    index: "05.05",
    date: "",
    title: "Spanish lessons",
    dek: "",
    body: "",
    tags: [],
    done: true,
  },
  {
    id: "painting-classes",
    section: "next",
    index: "05.01",
    date: "",
    title: "Professional watercolor, then oil painting classes",
    dek: "",
    body: "",
    tags: [],
  },
  {
    id: "atelier",
    section: "next",
    index: "05.02",
    date: "",
    title: "A London/Paris/Lisbon atelier, just to be",
    dek: "",
    body: "",
    tags: [],
  },
  {
    id: "wine-somm",
    section: "next",
    index: "05.03",
    date: "",
    title: "Wine somm",
    dek: "",
    body: "",
    tags: [],
  },
  {
    id: "milestone-birthday",
    section: "next",
    index: "05.04",
    date: "",
    title: "Milestone birthday celebrations",
    dek: "",
    body: "Stay tuned.",
    tags: [],
  },
];
