import type { Entry } from "./types";

/**
 * Every post on the site.
 * Add a new object to this list. See content/README.md for which section does what.
 * Order inside a section is the order on the page.
 */

export const ENTRIES: Entry[] = [
  {
    // Home base: local adventures in SF. Opens from the line under the map, not a numbered stop.
    // SAMPLE built from things you've mentioned; replace with your own and remove `draft`.
    id: "san-francisco",
    section: "destinations",
    homeBase: true,
    stamp: "⌂ HOME BASE",
    index: "01.00",
    date: "",
    place: "San Francisco",
    title: "San Francisco",
    dek: "Tourist in my own city.",
    body: [
      "* The café loop: Saint Frank, Spro, and Blue Bottle. Oat latte or oat cappuccino, depending on the day.\n* Cooking my way through the farmers market.\n* Coming up: the Symphony, a community dinner, and Bar Crenn.",
    ].join("\n\n"),
    tags: [],
    draft: true,
  },
  {
    id: "mendocino",
    section: "destinations",
    index: "01.04",
    date: "09.2026",
    place: "Mendocino",
    title: "Mendocino",
    dek: "Oddly felt like home.",
    body: "Waking up without an agenda. Staying at a vegan eco-friendly inn. Getting to know the locals at both Fort Bragg and Mendocino Village. Solo hikes (when Truffles was too tired) in the redwood forest. Secluded beaches for sunset. Oh and hanging out with horses, donkeys, llamas... I mean I never wanted to come back. Oddly felt like home",
    pin: [39.3077, -123.7995],
    arrive: "paddle",
    images: [
      "/destinations/mendocino/mendocino-01.jpg",
      "/destinations/mendocino/mendocino-02.jpg",
      "/destinations/mendocino/mendocino-03.jpg",
      "/destinations/mendocino/mendocino-04.jpg",
      "/destinations/mendocino/mendocino-05.jpg",
      "/destinations/mendocino/mendocino-06.jpg",
      "/destinations/mendocino/mendocino-07.jpg",
      "/destinations/mendocino/mendocino-08.jpg",
      "/destinations/mendocino/mendocino-09.jpg",
    ],
    imageAlts: [
      "Truffles resting in the shade of a pine on a bluff above a sandy cove and blue ocean",
      "Watercolors and brushes on a deck table, a flower painting in progress, Truffles wandering past purple blooms",
      "Driftwood glowing in late sun on a sandy riverbank across from a dark forest",
      "Rocks and a curling tide where the river meets the beach, hills lit orange at sunset",
      "Sunset over a beach and river mouth, driftwood at the water's edge",
      "Selfie on the rocky coast with Truffles, sea spray behind",
      "A river winding between forested hills and marsh under a soft cloudy sky",
      "Truffles eyeing a plate of dog treats on a patio table overlooking the hills",
      "Selfie on a wooden deck by a still lagoon, Truffles lying on the boards",
    ],
    imageAspects: [
      "landscape",
      "portrait",
      "landscape",
      "landscape",
      "landscape",
      "portrait",
      "landscape",
      "landscape",
      "landscape",
    ],
    tags: [],
  },
  {
    id: "hawaii",
    section: "destinations",
    index: "01.03",
    date: "07-08.2026",
    place: "Hawaii",
    title: "Hawaii",
    dek: "Outdoor showers only.",
    pin: [22.2, -159.5],
    arrive: "fly",
    body: "I basically moved my body all day and it felt great. But, my favorite part of the trip was taking outdoor showers while feeling the sun beating down, listening to the ocean + birds, and smelling a combination of lavender + nature ..... I can't tell you how much that regulated my nervous system. I don't think I took a shower indoors once that trip. Now if I could only do that in SF.",
    images: [
      "/hawaii/hawaii-01.jpg",
      "/hawaii/hawaii-02.jpg",
      "/hawaii/hawaii-03.jpg",
      "/hawaii/hawaii-04.jpg",
      "/hawaii/hawaii-05.jpg",
      "/hawaii/hawaii-06.jpg",
    ],
    imageAlts: [
      "Paddleboarding off a green headland",
      "Standing in shallow water beside an outrigger canoe",
      "Rooftop garden facing a sunset coast",
      "Night beach with a palm and kayaks",
      "On a catamaran under a yellow sail",
      "Feet toward a beach tree and the horizon",
    ],
    imageAspects: [
      "portrait",
      "landscape",
      "landscape",
      "portrait",
      "portrait",
      "portrait",
    ],
    tags: [],
  },

  {
    id: "colombia",
    section: "destinations",
    index: "01.02",
    date: "06.2026",
    place: "Colombia",
    title: "Colombia",
    dek: "Where I learned to salsa.",
    body: "[ Entry forthcoming. ]",
    pin: [6.2442, -75.5812],
    arrive: "fly",
    images: [
      "/destinations/colombia/colombia-01.jpg",
      "/destinations/colombia/colombia-02.jpg",
      "/destinations/colombia/colombia-03.jpg",
      "/destinations/colombia/colombia-04.jpg",
      "/destinations/colombia/colombia-05.jpg",
      "/destinations/colombia/colombia-06.jpg",
      "/destinations/colombia/colombia-07.jpg",
      "/destinations/colombia/colombia-08.jpg",
    ],
    imageAlts: [
      "A café with a live-edge wood bar and walls of bookshelves",
      "Two friends smiling and raising cocktails, one pale green, one berry red",
      "A hillside city of red-brick high-rises and green trees, seen from a treadmill",
      "Two friends at a dinner table holding up hands covered in chocolate",
      "Petit fours on charred wooden stands beside a glass of champagne",
      "A slice of chocolate cake with cream and two cortados on a concrete table",
      "Dancing salsa with a partner in a studio",
      "A black-and-white photo of a new floral tattoo on a shoulder blade",
    ],
    imageAspects: [
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
    ],
    // Where each photo was taken. Leave "" for no caption.
    imageCaptions: ["", "", "", "", "", "", "", ""],
    featured: [{ src: "/destinations/colombia/colombia-08.jpg" }],
    tags: [],
  },
  {
    id: "mexico-city",
    section: "destinations",
    index: "01.01",
    date: "06.2026",
    place: "Mexico City",
    title: "Mexico City",
    dek: "Mostly for food.",
    body: [
      "Mexico City holds a special place in my heart. This was my 4th trip there but I found so many new aspects of myself. Three highlights:",
      "* Experiencing the omakase tasting at Pujol where I serendipitously met Javi - an incredible human and winemaker at Peter Michael (Californians are everywhere). I was inspired by how much he loved what he did, the art and science being his craft, and that twinkle in his eye when he spoke about building his own thing. Something shifted inside of me and I sent my resignation letter right then and there. He said, “Well, I'll always remember this - meeting a stranger and being part of her quitting her job”. We ended up checking out the cocktail scene that night and I made a new friend that I can't wait to create more memories with\n* Discovered Xinu - obsessed with the intentionality and local ingredients that go into their perfumes. I tried verti-verde and left thinking this smells exactly how I feel. Needless to say I found my signature scent\n* Catching world cup games - the pure joy of connecting with others while rooting for Mexico. Everyone seemed to forget all of the divisions and turmoil in the world, and honestly it was SO NICE being away from the AI dystopia that is San Francisco. I had started to feel that I was the odd one out when I didn't want to talk about valuations, what AI tool you're building, and how we're all heading straight towards AGI -- rendering humans useless.",
    ].join("\n\n"),
    pin: [19.4326, -99.1332],
    arrive: "fly",
    images: [
      "/destinations/mexico-city/mexico-city-01.jpg",
      "/destinations/mexico-city/mexico-city-02.jpg",
      "/destinations/mexico-city/mexico-city-03.jpg",
      "/destinations/mexico-city/mexico-city-04.jpg",
      "/destinations/mexico-city/mexico-city-05.jpg",
      "/destinations/mexico-city/mexico-city-06.jpg",
      "/destinations/mexico-city/mexico-city-07.jpg",
      "/destinations/mexico-city/mexico-city-08.jpg",
      "/destinations/mexico-city/mexico-city-09.jpg",
      "/destinations/mexico-city/mexico-city-10.jpg",
    ],
    imageAlts: [
      "Three tacos on pink tortillas with a pink smoothie on a marble table",
      "A cup of gelato held up in front of the lit-up Don Nino gelateria at night",
      "Biting into a pastry from a paper bag in a leafy park",
      "A mirror selfie framed by smooth concrete walls",
      "A plated dessert beside a copy of Violeta by Isabel Allende, parrot wallpaper behind",
      "A tree-lined street corner with an old building, a red car and a crosswalk",
      "A Tout Chocolat takeaway cup on a wooden tray",
      "A chalkboard sign on the sidewalk: a soccer ball melting into chocolate",
      "A place setting with a pink Masala & Maíz menu and a denim napkin",
      "Mole sprinkled with sesame on a spotted ceramic plate at Pujol",
    ],
    imageAspects: [
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "landscape",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
    ],
    // Where each photo was taken. Leave "" for no caption.
    imageCaptions: [
      "La Pitahaya Vegana",
      "Don Nino gelateria",
      "Café Rosetta",
      "",
      "Panadería Rosetta",
      "",
      "Tout Chocolat",
      "",
      "Masala & Maíz",
      "Pujol",
    ],
    tags: [],
  },

  {
    id: "salsa-week-one",
    section: "play",
    hobby: "dance",
    index: "02.01",
    date: "06.2026",
    title: "Huh, salsa. Who knew?",
    dek: "",
    body: "My first week learning salsa, actually me in brown might even be my second day... and it taught me a lot. It allowed me to stop thinking so much and just be in my body. It was a flow state very different from what I've experienced when working (that cerebral locked-in flow vs being sensual and free). This was back in June and I've grown so much as a salsera since then ..... but one thing I'm still trying to overcome, the need for perfection before dancing with someone new. Come dance with me at Cigar bar in SF? We can make mistakes together :)",
    videos: [
      {
        src: "/play/salsa-01.mp4",
        poster: "/play/salsa-01.jpg",
        aspect: "portrait",
      },
      {
        src: "/play/salsa-02.mp4",
        poster: "/play/salsa-02.jpg",
        aspect: "portrait",
      },
    ],
    videoNote: "(My current teacher would kill me for how large my steps are here, but hey, at least I'm smiling.)",
    tags: [],
  },
  {
    // Opens the studio wall. Add paintings and notes in content/studio.ts.
    id: "studio",
    section: "play",
    hobby: "painting",
    index: "02.02",
    date: "",
    title: "The studio wall",
    dek: "More to come!",
    body: "",
    tags: [],
  },

  {
    id: "farmers-market",
    section: "play",
    hobby: "market",
    index: "02.03",
    date: "",
    title: "The weekend market",
    dek: "",
    body: "",
    // Add new photos to the END of a chapter's list, with the date as the caption.
    chapters: [
      {
        title: "For the table",
        body: "I've started putting together a bouquet from the market every week. They're beautiful and bring me joy.",
        photos: [
          { src: "/play/market/market-01.jpg", alt: "At the dining table with a bouquet of purple delphinium, Truffles lying on the rug below" },
          { src: "/play/market/market-02.jpg", alt: "Pink tulips in a glass vase, the city through the window behind" },
          { src: "/play/market/market-03.jpg", caption: "Jul 4", alt: "Orange lilies and pink blooms beside bowls of cherries, apricots and blackberries" },
          { src: "/play/market/market-04.jpg", caption: "Aug 23", alt: "Sunflowers and deep red amaranth in a vase by the window" },
          { src: "/play/market/market-05.jpg", caption: "Aug 29", alt: "Sunflowers and orange zinnias in a tall glass vase" },
          { src: "/play/market/market-06.jpg", caption: "Sep 20", alt: "A wildflower mix with a sunflower and pink cosmos by the window" },
        ],
      },
      {
        title: "For the plate",
        body: "",
        photos: [],
      },
    ],
    tags: [],
  },
  {
    // The typed page on the Play table: opens the list of ponderings (section "mood" below).
    id: "ponderings",
    section: "play",
    hobby: "writing",
    index: "02.04",
    date: "",
    title: "Ponderings",
    dek: "Longer thoughts, typed up. Some finished, some still brewing.",
    body: "",
    tags: [],
  },

  {
    id: "little-monk",
    section: "bookshelf",
    reading: true,
    index: "03.17",
    date: "",
    title: "The Little Monk and the Significance of Silence",
    spine: "The Little Monk",
    dek: "",
    body: "",
    tags: [],
  },
  {
    id: "violeta",
    section: "bookshelf",
    index: "03.01",
    date: "",
    title: "Violeta",
    dek: "Isabel Allende",
    body: "Picked up in Mexico City. Interesting read for historical fiction buffs and those who love a woman lead. I then found out the author is based in CA, of course.",
    tags: [],
  },
  {
    id: "summer-of-love",
    section: "bookshelf",
    index: "03.02",
    date: "",
    title: "Summer of Love",
    dek: "Kerri Maher",
    body: "I've fallen a bit out of love with SF recently, too much of an AI monolith for me. This book was the perfect read to romanticize SF and wine country, and it just had a great plot. Focused on women characters and familial bonds. This one seems to be circulating through friends for different reasons.",
    tags: [],
  },
  {
    id: "remains-of-the-day",
    section: "bookshelf",
    index: "03.03",
    date: "",
    title: "The Remains of the Day",
    spine: "Remains of the Day",
    dek: "Kazuo Ishiguro",
    body: "Honestly my favorite book of the past few months. Very relevant to why I decided to leave corporate and chase meaning and fulfillment. The ending was devastating, though (sorry for the spoiler). Thanks for the rec, Amar!",
    tags: [],
  },
  {
    id: "shampoo-effect",
    section: "bookshelf",
    index: "03.04",
    date: "",
    title: "The Shampoo Effect",
    dek: "Jenny Jackson",
    body: "",
    tags: [],
  },
  {
    id: "klara-and-the-sun",
    section: "bookshelf",
    index: "03.05",
    date: "",
    title: "Klara and the Sun",
    dek: "Kazuo Ishiguro",
    body: "Loved the writing, hated the plot. I got through it, but since it was very AI-coded, it left me feeling uneasy about the future of humanity. Then, on top of that, I had a conversation about augmented humans, and humans preferring relationships with someone “perfect” for them, or with an AI. I can't stomach this.",
    tags: [],
  },
  {
    id: "heartburn",
    section: "bookshelf",
    index: "03.06",
    date: "",
    title: "Heartburn",
    dek: "Nora Ephron",
    body: "A great laugh, nothing too serious. Thanks for the rec, Nitisha!",
    tags: [],
  },
  {
    id: "last-days-of-socrates",
    section: "bookshelf",
    index: "03.07",
    date: "",
    title: "The Last Days of Socrates",
    spine: "Socrates",
    dek: "Plato",
    body: "Just feeds my endless curiosity right now.",
    tags: [],
  },
  {
    id: "strangers",
    section: "bookshelf",
    index: "03.08",
    date: "",
    title: "Strangers - A Marriage Memoir",
    spine: "Strangers",
    dek: "Belle Burden",
    body: "Beautifully written, so raw and real. Building a life with someone is a funny thing: completely intimate and in sync one day, and blindsided the next. You can go years not really knowing what's going on in their head, and one day just be strangers in passing.",
    tags: [],
  },
  {
    id: "yesteryear",
    section: "bookshelf",
    index: "03.09",
    date: "",
    title: "Yesteryear",
    dek: "Caro Claire Burke",
    body: "A bit hyped (somehow we were reading this at the same time and didn't even know, Omi!), but it got me thinking about those who oppose progress vs. those who jump on the progress bandwagon just for the sake of progress. Again, this ties back to the AI angst for me: what's the right balance?",
    tags: [],
  },
  {
    id: "how-to-be-perfect",
    section: "bookshelf",
    index: "03.10",
    date: "",
    title: "How to Be Perfect",
    dek: "Michael Schur",
    body: "",
    tags: [],
  },
  {
    id: "monogamy",
    section: "bookshelf",
    index: "03.11",
    date: "",
    title: "Monogamy",
    dek: "Sue Miller",
    body: "A bit underwhelming. Doesn't offer a fresh take on non-monogamy lifestyles and I lost interest about half way through. Too surface level for me.",
    tags: [],
  },
  {
    id: "nicomachean-ethics",
    section: "bookshelf",
    index: "03.15",
    date: "",
    title: "Nicomachean Ethics",
    dek: "Aristotle",
    body: "Still trying to figure out what the right balance of each virtue is, but I do agree that relationships are key to a flourishing life. Thanks for the rec, Sid, and for helping me figure out where to start, ha.",
    tags: [],
  },
  {
    id: "gentleman-in-moscow",
    section: "bookshelf",
    index: "03.16",
    date: "",
    title: "A Gentleman in Moscow",
    dek: "Amor Towles",
    body: "Was supposed to be similar to Remains of the Day, but I just couldn't get through it. The writing is extremely slow, flowery, and chock-full of references. DNF for me.",
    tags: [],
  },

  // Podcasts: they live on the iPod, top of the list first.
  {
    id: "stories-of-art",
    section: "bookshelf",
    format: "podcast",
    index: "03.18",
    date: "",
    title: "Stories of Art",
    dek: "HENI Talks",
    body: "",
    tags: [],
  },
  {
    id: "the-book-review",
    section: "bookshelf",
    format: "podcast",
    index: "03.24",
    date: "",
    title: "The Book Review",
    dek: "The New York Times",
    body: "",
    tags: [],
  },
  {
    id: "sex-with-emily",
    section: "bookshelf",
    format: "podcast",
    index: "03.19",
    date: "",
    title: "Sex with Emily",
    dek: "Dr. Emily Morse",
    body: "",
    tags: [],
  },
  {
    id: "the-happiness-lab",
    section: "bookshelf",
    format: "podcast",
    index: "03.20",
    date: "",
    title: "The Happiness Lab",
    dek: "Dr. Laurie Santos",
    body: "",
    tags: [],
  },
  {
    id: "hidden-brain",
    section: "bookshelf",
    format: "podcast",
    index: "03.25",
    date: "",
    title: "Hidden Brain",
    dek: "Shankar Vedantam",
    body: "",
    tags: [],
  },
  {
    id: "where-should-we-begin",
    section: "bookshelf",
    format: "podcast",
    index: "03.21",
    date: "",
    title: "Where Should We Begin?",
    dek: "Esther Perel",
    body: "",
    tags: [],
  },
  {
    id: "prof-g-markets",
    section: "bookshelf",
    format: "podcast",
    index: "03.22",
    date: "",
    title: "Prof G Markets",
    dek: "Scott Galloway",
    body: "",
    tags: [],
  },
  {
    id: "conan-needs-a-friend",
    section: "bookshelf",
    format: "podcast",
    index: "03.23",
    date: "",
    title: "Conan O'Brien Needs a Friend",
    dek: "Conan O'Brien",
    body: "",
    tags: [],
  },

  {
    id: "think-and-we-are",
    section: "mood",
    index: "04.04",
    date: "",
    title: "Can you hold both at once?",
    dek: "Work in progress.",
    body: "How to hold both of these at once, “I think, therefore I am” and “I am because we are”, and what they mean to me.",
    tags: [],
  },
  {
    id: "solitude-vs-loneliness",
    section: "mood",
    index: "04.06",
    date: "",
    title: "Solitude vs. loneliness",
    dek: "Work in progress.",
    body: "",
    tags: [],
  },
  {
    id: "not-a-zero-sum-game",
    section: "mood",
    index: "04.07",
    date: "",
    title: "It's not a zero-sum game",
    dek: "Thoughts on monogamy. Work in progress.",
    body: "",
    tags: [],
  },
  {
    id: "intentional-pauses",
    section: "mood",
    index: "04.08",
    date: "",
    title: "The women taking intentional pauses",
    dek: "Themes from all of the amazing women I've met doing the same. Work in progress.",
    body: "",
    tags: [],
  },
  {
    id: "productivity-and-mastery",
    section: "mood",
    index: "04.09",
    date: "",
    title: "Why are we all so obsessed with productivity and mastery?",
    dek: "Work in progress.",
    body: "",
    tags: [],
  },
  {
    id: "ritual-of-coffee",
    section: "mood",
    index: "04.05",
    date: "08.28.2026",
    title: "The Ritual of Coffee",
    dek: "",
    body: [
      "That first sip feels like relief. The warming layers, the smoothness, such a delicate balance of flavors, and the immediate signal to my brain that it's go time.",
      "The power of a ritual is that it's different from a habit or doing something for the sake of the function. It's a bit more sacred, almost spiritual, and always intentional. It becomes so essential and ingrained in your life that taking it away feels unsettling.",
      "So is it the ritual itself, or the object? Is it the stimulant hitting the nervous system, or, if you believe in this stuff, the soul? If I had to wager, it's the deeper meaning, often tied to pleasure, even in a quiet, subtle way. It's less a hit of dopamine and more the gentle steadiness of a morning walk with your pup, or a slow skincare routine. That's the magic of coffee for me.",
      "From the second I wake up, it doesn't matter where in the world I am, what yesterday looked like, or what today holds. I know this part is mine. Once I'm out, there might be a delightful surprise in a new café or a chance conversation. Walking into a café feels like a common thread that connects people across cultures. I could be in India, in Paris, in Colombia, and immediately feel like I belong, like I have a space to settle if I want to. I can dive into conversation or stay a wallflower sipping my cup.",
      "And it doesn't have to be somewhere far away. The cafés I cycle between, Saint Frank, Spro, and Blue Bottle, are all within a five-minute walk, and they feel just as sacred. My order is an oat latte or an oat cappuccino, depending on the day. Close to home, it's a mix of flavor, pleasure, familiarity, and groundedness, and these days very little about utility. I feel like I'm part of a community.",
      "Funny thing is, I call it the magic of coffee, yet it's not really about the coffee at all. It has to be palatable, sure. I know good beans, enough to be competent without being a snob, but it doesn't even matter how good the drink is. And still, nothing else will do. I'm not as satisfied or grounded when I have chai. I have a relationship with coffee that can't be replaced, at least if we're staying in the realm of ritual and keeping utility at arm's length.",
      "I'm not sure coffee was always a ritual for me. In school it was survival, obscene amounts of it during finals just to stay upright over a textbook. Later it was fuel, gulped between meetings to get through the workday. Somewhere after I stepped away from that life, it changed. With nowhere to rush to, the cup slowed down with me. I'm trying to be more intentional now, to observe and listen to what's around me, and to make decisions outside the fight-or-flight mode I lived in for so long. Maybe that's how a habit becomes a ritual. You finally start paying attention to it, and to the intention behind it.",
      "So now I'm curious about yours. Is there something small you do that feels more sacred than routine, more than necessity? When did it become a ritual for you, and what happens when you skip it? For me, the day just feels a bit incomplete. I can't tell you how many coffees I had in Kona with absolutely zero need to be caffeinated.",
    ].join("\n\n"),
    tags: [],
  },

  {
    id: "spanish-lessons",
    section: "next",
    index: "05.05",
    date: "",
    title: "Spanish lessons",
    dek: "",
    body: "",
    tags: [],
    done: true,
  },
  {
    id: "painting-classes",
    section: "next",
    index: "05.01",
    date: "",
    title: "Professional watercolor, then oil painting classes",
    dek: "",
    body: "",
    tags: [],
  },
  {
    id: "atelier",
    section: "next",
    index: "05.02",
    date: "",
    title: "A London/Paris/Lisbon atelier, just to be",
    dek: "",
    body: "",
    tags: [],
  },
  {
    id: "wine-somm",
    section: "next",
    index: "05.03",
    date: "",
    title: "Wine somm",
    dek: "",
    body: "",
    tags: [],
  },
  {
    id: "third-space",
    section: "next",
    index: "05.06",
    date: "",
    title: "Build a third space, or a Paris-style salon",
    dek: "",
    body: "",
    tags: [],
  },
  {
    id: "milestone-birthday",
    section: "next",
    index: "05.04",
    date: "",
    title: "Milestone birthday celebrations",
    dek: "",
    body: "Stay tuned.",
    tags: [],
  },
];
