import type { Entry } from "./types";

/**
 * Every post on the site.
 * Add a new object to this list. See content/README.md for which section does what.
 * Order inside a section is the order on the page.
 */

function placeholder(
  id: string,
  section: Entry["section"],
  index: string,
  date: string,
): Entry {
  return {
    id,
    section,
    index,
    date,
    title: `Untitled — Entry ${index}`,
    spine: "Untitled",
    dek: "Awaiting dispatch.",
    body: "[ Entry forthcoming. ]",
    tags: [],
    draft: true,
  };
}

export const ENTRIES: Entry[] = [
  {
    id: "mexico-city",
    section: "destinations",
    index: "01.01",
    date: "06.2026",
    place: "Mexico City",
    title: "Mexico City",
    dek: "Mostly for food.",
    body: [
      "Mexico City holds a special place in my heart. This was my 4th trip there but I found so many new aspects of myself. Three highlights:",
      "* Experiencing the omakase tasting at Pujol where I serendipitously met Javi - an incredible human and winemaker at Peter Michael (Californians are everywhere). I was inspired by how much he loved what he did, the art and science being his craft, and that twinkle in his eye when he spoke about building his own thing. Something shifted inside of me and I sent my resignation letter right then and there. He said, “Well, I'll always remember this - meeting a stranger and being part of her quitting her job”. We ended up checking out the cocktail scene that night and I made a new friend that I can't wait to create more memories with\n* Discovered Xinu - obsessed with the intentionality and local ingredients that go into their perfumes. I tried verti-verde and left thinking this smells exactly how I feel. Needless to say I found my signature scent\n* Catching world cup games - the pure joy of connecting with others while rooting for Mexico. Everyone seemed to forget all of the divisions and turmoil in the world, and honestly it was SO NICE being away from the AI dystopia that is San Francisco. I had started to feel that I was the odd one out when I didn't want to talk about valuations, what AI tool you're building, and how we're all heading straight towards AGI -- rendering humans useless.",
    ].join("\n\n"),
    pin: [19.4326, -99.1332],
    arrive: "fly",
    images: [
      "/destinations/mexico-city/mexico-city-01.jpg",
      "/destinations/mexico-city/mexico-city-02.jpg",
      "/destinations/mexico-city/mexico-city-03.jpg",
      "/destinations/mexico-city/mexico-city-04.jpg",
      "/destinations/mexico-city/mexico-city-05.jpg",
      "/destinations/mexico-city/mexico-city-06.jpg",
      "/destinations/mexico-city/mexico-city-07.jpg",
      "/destinations/mexico-city/mexico-city-08.jpg",
      "/destinations/mexico-city/mexico-city-09.jpg",
      "/destinations/mexico-city/mexico-city-10.jpg",
    ],
    imageAlts: [
      "Three tacos on pink tortillas with a pink smoothie on a marble table",
      "A cup of gelato held up in front of the lit-up Don Nino gelateria at night",
      "Biting into a pastry from a paper bag in a leafy park",
      "A mirror selfie framed by smooth concrete walls",
      "A plated dessert beside a copy of Violeta by Isabel Allende, parrot wallpaper behind",
      "A tree-lined street corner with an old building, a red car and a crosswalk",
      "A Tout Chocolat takeaway cup on a wooden tray",
      "A chalkboard sign on the sidewalk: a soccer ball melting into chocolate",
      "A place setting with a pink Masala & Maíz menu and a denim napkin",
      "Mole sprinkled with sesame on a spotted ceramic plate at Pujol",
    ],
    imageAspects: [
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "landscape",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
      "portrait",
    ],
    // Where each photo was taken. Leave "" for no caption.
    imageCaptions: [
      "",
      "Don Nino gelateria",
      "Café Rosetta",
      "",
      "Panadería Rosetta",
      "",
      "Tout Chocolat",
      "",
      "Masala & Maíz",
      "Pujol",
    ],
    tags: [],
  },

  {
    id: "colombia",
    section: "destinations",
    index: "01.02",
    date: "09.20.2026",
    place: "Colombia",
    title: "Colombia",
    dek: "Where I learned to salsa.",
    body: "[ Entry forthcoming. ]",
    pin: [4.6, -74.1],
    arrive: "fly",
    tags: [],
  },
  {
    id: "hawaii",
    section: "destinations",
    index: "01.03",
    date: "09.16.2026",
    place: "Hawaii",
    title: "Hawaii",
    dek: "Nature and movement.",
    pin: [22.2, -159.5],
    arrive: "paddle",
    body: "[ Entry forthcoming. ]",
    images: [
      "/hawaii/hawaii-01.jpg",
      "/hawaii/hawaii-02.jpg",
      "/hawaii/hawaii-03.jpg",
      "/hawaii/hawaii-04.jpg",
      "/hawaii/hawaii-05.jpg",
      "/hawaii/hawaii-06.jpg",
    ],
    imageAlts: [
      "Paddleboarding off a green headland",
      "Standing in shallow water beside an outrigger canoe",
      "Rooftop garden facing a sunset coast",
      "Night beach with a palm and kayaks",
      "On a catamaran under a yellow sail",
      "Feet toward a beach tree and the horizon",
    ],
    imageAspects: [
      "portrait",
      "landscape",
      "landscape",
      "portrait",
      "portrait",
      "portrait",
    ],
    tags: [],
  },
  {
    id: "mendocino",
    section: "destinations",
    index: "01.04",
    date: "09.04.2026",
    place: "Mendocino",
    title: "Mendocino",
    dek: "Oddly felt like home.",
    body: "Waking up without an agenda. Staying at a vegan eco-friendly inn. Getting to know the locals at both Fort Bragg and Mendocino Village. Solo hikes (when Truffles was too tired) in the redwood forest. Secluded beaches for sunset. Oh and hanging out with horses, donkeys, llamas... I mean I never wanted to come back. Oddly felt like home",
    pin: [39.3077, -123.7995],
    arrive: "drive",
    images: [
      "/destinations/mendocino/mendocino-01.jpg",
      "/destinations/mendocino/mendocino-02.jpg",
      "/destinations/mendocino/mendocino-03.jpg",
      "/destinations/mendocino/mendocino-04.jpg",
      "/destinations/mendocino/mendocino-05.jpg",
      "/destinations/mendocino/mendocino-06.jpg",
      "/destinations/mendocino/mendocino-07.jpg",
      "/destinations/mendocino/mendocino-08.jpg",
      "/destinations/mendocino/mendocino-09.jpg",
    ],
    imageAlts: [
      "Truffles resting in the shade of a pine on a bluff above a sandy cove and blue ocean",
      "Watercolors and brushes on a deck table, a flower painting in progress, Truffles wandering past purple blooms",
      "Driftwood glowing in late sun on a sandy riverbank across from a dark forest",
      "Rocks and a curling tide where the river meets the beach, hills lit orange at sunset",
      "Sunset over a beach and river mouth, driftwood at the water's edge",
      "Selfie on the rocky coast with Truffles, sea spray behind",
      "A river winding between forested hills and marsh under a soft cloudy sky",
      "Truffles eyeing a plate of dog treats on a patio table overlooking the hills",
      "Selfie on a wooden deck by a still lagoon, Truffles lying on the boards",
    ],
    imageAspects: [
      "landscape",
      "portrait",
      "landscape",
      "landscape",
      "landscape",
      "portrait",
      "landscape",
      "landscape",
      "landscape",
    ],
    tags: [],
  },

  { ...placeholder("ink-study-01", "play", "02.01", "09.06.2026"), hobby: "dance" },
  {
    // Opens the studio wall. Add paintings and notes in content/studio.ts.
    id: "studio",
    section: "play",
    hobby: "painting",
    index: "02.02",
    date: "",
    title: "The studio wall",
    dek: "",
    body: "",
    tags: [],
  },

  { ...placeholder("botanical-field", "play", "02.03", "09.14.2026"), hobby: "cooking" },
  { ...placeholder("contact-sheet", "play", "02.04", "09.18.2026"), hobby: "writing" },

  placeholder("plato-republic", "bookshelf", "03.01", "09.05.2026"),
  placeholder("socratic-method", "bookshelf", "03.02", "09.10.2026"),
  placeholder("aristotle-ethics", "bookshelf", "03.03", "09.15.2026"),
  placeholder("canon-shelf", "bookshelf", "03.04", "09.19.2026"),
  placeholder("bookshelf-05", "bookshelf", "03.05", "09.20.2026"),
  placeholder("bookshelf-06", "bookshelf", "03.06", "09.20.2026"),
  placeholder("bookshelf-07", "bookshelf", "03.07", "09.21.2026"),
  placeholder("bookshelf-08", "bookshelf", "03.08", "09.21.2026"),
  placeholder("bookshelf-09", "bookshelf", "03.09", "09.22.2026"),
  placeholder("bookshelf-10", "bookshelf", "03.10", "09.22.2026"),

  placeholder("mood-log-01", "mood", "04.01", "09.07.2026"),
  placeholder("mood-log-02", "mood", "04.02", "09.13.2026"),
  placeholder("mood-log-03", "mood", "04.03", "09.18.2026"),
  placeholder("mood-log-04", "mood", "04.04", "09.22.2026"),

  placeholder("on-leaving", "next", "05.01", "09.03.2026"),
  placeholder("trajectories", "next", "05.02", "09.12.2026"),
  placeholder("unlearning", "next", "05.03", "09.17.2026"),
  placeholder("after-the-year", "next", "05.04", "09.21.2026"),
];
